"use client";

import React from "react";
import { useRouter } from "next/navigation";
import {
  Button,
  SectionBreak,
  Main,
  H1,
  Analytics,
  WarningText,
} from "@/app/components";
import LandingItem from "./LandingItem";
import styles from "./Landing.module.css";
import { clearHistory, clearLocation } from "@/app/utils";

export default function Landing() {
  const router = useRouter();

  /**
   * Start a chat by initiating a session and route pushed to /chat
   *
   * @returns void
   */
  const startChat = () => {
    clearHistory();
    clearLocation();
    router.push("/chat");
  };

  return (
    <Main>
      <Analytics />
      <div className={styles.login} data-testid="landing-container">
        <H1 data-testid="landing-heading">Using AI Responsibly</H1>
        <SectionBreak level="m" visible={false} />

        <LandingItem
          className={styles.landingDescription}
          data-testid="landing-description"
          text="This tool uses AI to help you find Universal Learning guidance."
        />

        <LandingItem
          className={styles.landingListTitle}
          data-testid="landing-list-title"
          text="It searches the guidance and produces summaries in response to your
          questions."
        />

        <LandingItem
          text="AI-generated summaries may contain errors. You must the Universal
          Learning guidance to check they are accurate before acting on them."
        />

        <LandingItem
          text="The summaries generated by this tool do not replace DWP’s official
          policy or guidance."
        />

        <LandingItem
          text="You are responsible for making sure your actions and advice to
          claimants are correct and in line with Universal Credit policy."
        />

        <WarningText>
          Do not enter information that can identify your claimant, such as
          their real name, contact details or banking information.
        </WarningText>
        <SectionBreak level="m" visible={false} />

        <Button
          data-testid="landing-start-chat-button"
          aria-label="Agree and continue"
          start
          onClick={startChat}
        >
          Agree and Continue
        </Button>
      </div>
    </Main>
  );
}
